### ISSUE TITLE
scrollbars visible and "hello-world" not displaying correctly

### ISSUE THREAD

**Issue by thinusn** [themekit/adminplus-boilerplate-laravel#1]
It seems like the scrollbars are visible and the `Hello World` test gets cut off by the breadcrumbs menu/header. I tried it on the demo site and locally. 

Im using Chrome Version 48.0.2564.116 m on Windows 10

![scrollbars_visible](https://cloud.githubusercontent.com/assets/5155028/13706640/9973c794-e7ae-11e5-8adf-dc0312a138e9.jpg)

**Comment by lazabogdan** [comment]
Hi,

Thanks for letting us know. The issue is most probably from [bootstrap-layout](https://github.com/themekit/bootstrap-layout) and it's a windows only issue. Looks ok on OS X http://d.pr/i/17NTd

Anyway, we'll fix it as soon as possible. I've opened the issue on bootstrap-layout.
Thanks

**Comment by lazabogdan** [comment]
@thinusn Should be fixed now.
